#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 10 10:41:47 2021

@author: joseph
"""
try:
   account_holder = input("Account Holder: ")
   deposit1 = float(input("Month 1 Deposit: "))
   deposit2 = float(input("Month 2 Deposit: "))
   deposit3 = float(input("Month 3 Deposit: "))
   deposit4 = float(input("Month 4 Deposit: "))
   total = deposit1 + deposit2 + deposit3 + deposit4
   print("Hello " + account_holder + ", welcome to Gables Bank.")
   print("You deposited in total: ${:.2f}".format(total))
   deposits = int(input("How many deposits did you make? "))
   avg_deposits = total/deposits
   print("Your average deposit is: {:.2f}".format(avg_deposits))
except ZeroDivisionError:
    print("You didnt make any deposits?????")

except ValueError:
    print("You gave an improper deposit value.")

finally:
    print("Thank you for using Gables Bank.")
